In [1]:
import os
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers, models, Sequential

(x_in, y_in), (x_val, y_val) = keras.datasets.mnist.load_data()

network = Sequential([
            layers.Conv2D(6, kernel_size=3, strides=1), 
            layers.MaxPooling2D(pool_size=2, strides=2),
            layers.ReLU(),
            layers.Conv2D(16, kernel_size=3, strides=1),
            layers.MaxPooling2D(pool_size=2, strides=2),
            layers.ReLU(),
            layers.Flatten(),
            layers.Dense(120),
            layers.ReLU(),
            layers.Dense(84),
            layers.ReLU(),
            layers.Dense(10),
            layers.Softmax() # 如果使用CategoricalCrossentropy(from_logits=True)，则不加这句
])
# network.build(input_shape=(4, 28, 28, 1)) # 这里的4即为后面的batch_size
# network.summary()

# 训练网络
'''
x_in = tf.expand_dims((tf.convert_to_tensor(x_in, dtype=tf.float32) / 255.0), axis=-1)
y_in = tf.one_hot(tf.convert_to_tensor(y_in, dtype=tf.int32), depth=10)
train_data = tf.data.Dataset.from_tensor_slices((x_in, y_in)) # 注意这里的括号层数，只能接收一个变量
train_data = train_data.batch(4)


# 通过设定from_logits=True标志位将softmax激活函数实现在损失函数中，这样就不需要手动添加损失函数，提升数值计算稳定性。
# 是否可以理解为在训练时避免使用softmax，能够提升训练效果，需要时再用softmax输出为概率
criteon = keras.losses.CategoricalCrossentropy(from_logits=True) 
optimizer = keras.optimizers.Adam(learning_rate=0.001)


for epoch in range(1):
    for step, (x, y) in enumerate(train_data):
        with tf.GradientTape() as tape:
            # 前向计算
            out = network(x)
            # 计算交叉熵损失函数，标量
            loss = criteon(y, out)
        # 梯度计算、优化
        grads = tape.gradient(loss, network.trainable_variables)
        optimizer.apply_gradients(zip(grads, network.trainable_variables))
        if step%4 == 0 :
            print(epoch, loss)
'''

x_in = tf.expand_dims((tf.convert_to_tensor(x_in, dtype=tf.float32) / 255.0), axis=-1)
y_in = tf.one_hot(tf.convert_to_tensor(y_in, dtype=tf.int32), depth=10)

print(x_in.shape)
network.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy']) # 使用交叉熵作为loss函数    

network.fit(x_in, y_in, batch_size=4, epochs=1, 
             validation_split=0.1)

(60000, 28, 28, 1)
Train on 54000 samples, validate on 6000 samples
54000/54000 [==============================] - 134s 2ms/sample - loss: 0.1401 - accuracy: 0.9567 - val_loss: 0.0708 - val_accuracy: 0.9815


In [3]:
network.save('mnist-lenet5.h5')

In [ ]:
del model

In [ ]:
network = models.load_model('mnist-lenet5.h5')

In [ ]:
(x_in, y_in), (x_val, y_val) = keras.datasets.mnist.load_data()
x_val = tf.convert_to_tensor(x_val/255.0, dtype=tf.float32)
y_val = tf.convert_to_tensor(y_val, dtype=tf.int32)
test_dataset = tf.data.Dataset.from_tensor_slices((x_val, y_val))
test_dataset = test_dataset.batch(1)
# 测试模型
correct, total = 0, 0
for x, y in test_dataset:
    x = tf.expand_dims(x, axis=-1)
    out = network(x)
    # softmax不改变元素大小相对关系，因此省去（以概率选择第一个值时，都可以省去？）
    pred = tf.argmax(out, axis=-1) 
    y = tf.cast(y, tf.int64)
    correct += float(tf.reduce_sum(tf.cast(tf.equal(pred, y), tf.float32)))
    total += x.shape[0]
    print(total, tf.equal(pred, y))
print('test acc:', correct/total)


1 tf.Tensor([ True], shape=(1,), dtype=bool)
2 tf.Tensor([ True], shape=(1,), dtype=bool)
3 tf.Tensor([ True], shape=(1,), dtype=bool)
4 tf.Tensor([ True], shape=(1,), dtype=bool)
5 tf.Tensor([ True], shape=(1,), dtype=bool)
6 tf.Tensor([ True], shape=(1,), dtype=bool)
7 tf.Tensor([ True], shape=(1,), dtype=bool)
8 tf.Tensor([ True], shape=(1,), dtype=bool)
9 tf.Tensor([ True], shape=(1,), dtype=bool)
10 tf.Tensor([ True], shape=(1,), dtype=bool)
11 tf.Tensor([ True], shape=(1,), dtype=bool)
12 tf.Tensor([ True], shape=(1,), dtype=bool)
13 tf.Tensor([ True], shape=(1,), dtype=bool)
14 tf.Tensor([ True], shape=(1,), dtype=bool)
15 tf.Tensor([ True], shape=(1,), dtype=bool)
16 tf.Tensor([ True], shape=(1,), dtype=bool)
17 tf.Tensor([ True], shape=(1,), dtype=bool)
18 tf.Tensor([ True], shape=(1,), dtype=bool)
19 tf.Tensor([ True], shape=(1,), dtype=bool)
20 tf.Tensor([ True], shape=(1,), dtype=bool)
21 tf.Tensor([ True], shape=(1,), dtype=bool)
22 tf.Tensor([ True], shape=(1,), dtype=boo

194 tf.Tensor([ True], shape=(1,), dtype=bool)
195 tf.Tensor([ True], shape=(1,), dtype=bool)
196 tf.Tensor([ True], shape=(1,), dtype=bool)
197 tf.Tensor([ True], shape=(1,), dtype=bool)
198 tf.Tensor([ True], shape=(1,), dtype=bool)
199 tf.Tensor([ True], shape=(1,), dtype=bool)
200 tf.Tensor([ True], shape=(1,), dtype=bool)
201 tf.Tensor([ True], shape=(1,), dtype=bool)
202 tf.Tensor([ True], shape=(1,), dtype=bool)
203 tf.Tensor([ True], shape=(1,), dtype=bool)
204 tf.Tensor([ True], shape=(1,), dtype=bool)
205 tf.Tensor([ True], shape=(1,), dtype=bool)
206 tf.Tensor([ True], shape=(1,), dtype=bool)
207 tf.Tensor([ True], shape=(1,), dtype=bool)
208 tf.Tensor([ True], shape=(1,), dtype=bool)
209 tf.Tensor([ True], shape=(1,), dtype=bool)
210 tf.Tensor([ True], shape=(1,), dtype=bool)
211 tf.Tensor([ True], shape=(1,), dtype=bool)
212 tf.Tensor([ True], shape=(1,), dtype=bool)
213 tf.Tensor([ True], shape=(1,), dtype=bool)
214 tf.Tensor([ True], shape=(1,), dtype=bool)
215 tf.Tensor

370 tf.Tensor([ True], shape=(1,), dtype=bool)
371 tf.Tensor([ True], shape=(1,), dtype=bool)
372 tf.Tensor([ True], shape=(1,), dtype=bool)
373 tf.Tensor([ True], shape=(1,), dtype=bool)
374 tf.Tensor([ True], shape=(1,), dtype=bool)
375 tf.Tensor([ True], shape=(1,), dtype=bool)
376 tf.Tensor([ True], shape=(1,), dtype=bool)
377 tf.Tensor([ True], shape=(1,), dtype=bool)
378 tf.Tensor([ True], shape=(1,), dtype=bool)
379 tf.Tensor([ True], shape=(1,), dtype=bool)
380 tf.Tensor([ True], shape=(1,), dtype=bool)
381 tf.Tensor([ True], shape=(1,), dtype=bool)
382 tf.Tensor([ True], shape=(1,), dtype=bool)
383 tf.Tensor([ True], shape=(1,), dtype=bool)
384 tf.Tensor([ True], shape=(1,), dtype=bool)
385 tf.Tensor([ True], shape=(1,), dtype=bool)
386 tf.Tensor([ True], shape=(1,), dtype=bool)
387 tf.Tensor([ True], shape=(1,), dtype=bool)
388 tf.Tensor([ True], shape=(1,), dtype=bool)
389 tf.Tensor([ True], shape=(1,), dtype=bool)
390 tf.Tensor([ True], shape=(1,), dtype=bool)
391 tf.Tensor

556 tf.Tensor([ True], shape=(1,), dtype=bool)
557 tf.Tensor([ True], shape=(1,), dtype=bool)
558 tf.Tensor([ True], shape=(1,), dtype=bool)
559 tf.Tensor([ True], shape=(1,), dtype=bool)
560 tf.Tensor([ True], shape=(1,), dtype=bool)
561 tf.Tensor([ True], shape=(1,), dtype=bool)
562 tf.Tensor([ True], shape=(1,), dtype=bool)
563 tf.Tensor([ True], shape=(1,), dtype=bool)
564 tf.Tensor([ True], shape=(1,), dtype=bool)
565 tf.Tensor([ True], shape=(1,), dtype=bool)
566 tf.Tensor([ True], shape=(1,), dtype=bool)
567 tf.Tensor([ True], shape=(1,), dtype=bool)
568 tf.Tensor([ True], shape=(1,), dtype=bool)
569 tf.Tensor([ True], shape=(1,), dtype=bool)
570 tf.Tensor([ True], shape=(1,), dtype=bool)
571 tf.Tensor([ True], shape=(1,), dtype=bool)
572 tf.Tensor([ True], shape=(1,), dtype=bool)
573 tf.Tensor([ True], shape=(1,), dtype=bool)
574 tf.Tensor([ True], shape=(1,), dtype=bool)
575 tf.Tensor([ True], shape=(1,), dtype=bool)
576 tf.Tensor([ True], shape=(1,), dtype=bool)
577 tf.Tensor

746 tf.Tensor([ True], shape=(1,), dtype=bool)
747 tf.Tensor([ True], shape=(1,), dtype=bool)
748 tf.Tensor([ True], shape=(1,), dtype=bool)
749 tf.Tensor([ True], shape=(1,), dtype=bool)
750 tf.Tensor([ True], shape=(1,), dtype=bool)
751 tf.Tensor([ True], shape=(1,), dtype=bool)
752 tf.Tensor([ True], shape=(1,), dtype=bool)
753 tf.Tensor([ True], shape=(1,), dtype=bool)
754 tf.Tensor([ True], shape=(1,), dtype=bool)
755 tf.Tensor([ True], shape=(1,), dtype=bool)
756 tf.Tensor([ True], shape=(1,), dtype=bool)
757 tf.Tensor([ True], shape=(1,), dtype=bool)
758 tf.Tensor([ True], shape=(1,), dtype=bool)
759 tf.Tensor([ True], shape=(1,), dtype=bool)
760 tf.Tensor([ True], shape=(1,), dtype=bool)
761 tf.Tensor([ True], shape=(1,), dtype=bool)
762 tf.Tensor([ True], shape=(1,), dtype=bool)
763 tf.Tensor([ True], shape=(1,), dtype=bool)
764 tf.Tensor([ True], shape=(1,), dtype=bool)
765 tf.Tensor([ True], shape=(1,), dtype=bool)
766 tf.Tensor([ True], shape=(1,), dtype=bool)
767 tf.Tensor

925 tf.Tensor([False], shape=(1,), dtype=bool)
926 tf.Tensor([ True], shape=(1,), dtype=bool)
927 tf.Tensor([ True], shape=(1,), dtype=bool)
928 tf.Tensor([ True], shape=(1,), dtype=bool)
929 tf.Tensor([ True], shape=(1,), dtype=bool)
930 tf.Tensor([ True], shape=(1,), dtype=bool)
931 tf.Tensor([ True], shape=(1,), dtype=bool)
932 tf.Tensor([ True], shape=(1,), dtype=bool)
933 tf.Tensor([ True], shape=(1,), dtype=bool)
934 tf.Tensor([ True], shape=(1,), dtype=bool)
935 tf.Tensor([ True], shape=(1,), dtype=bool)
936 tf.Tensor([ True], shape=(1,), dtype=bool)
937 tf.Tensor([ True], shape=(1,), dtype=bool)
938 tf.Tensor([ True], shape=(1,), dtype=bool)
939 tf.Tensor([False], shape=(1,), dtype=bool)
940 tf.Tensor([ True], shape=(1,), dtype=bool)
941 tf.Tensor([ True], shape=(1,), dtype=bool)
942 tf.Tensor([ True], shape=(1,), dtype=bool)
943 tf.Tensor([ True], shape=(1,), dtype=bool)
944 tf.Tensor([ True], shape=(1,), dtype=bool)
945 tf.Tensor([ True], shape=(1,), dtype=bool)
946 tf.Tensor

1118 tf.Tensor([ True], shape=(1,), dtype=bool)
1119 tf.Tensor([ True], shape=(1,), dtype=bool)
1120 tf.Tensor([ True], shape=(1,), dtype=bool)
1121 tf.Tensor([ True], shape=(1,), dtype=bool)
1122 tf.Tensor([ True], shape=(1,), dtype=bool)
1123 tf.Tensor([ True], shape=(1,), dtype=bool)
1124 tf.Tensor([ True], shape=(1,), dtype=bool)
1125 tf.Tensor([ True], shape=(1,), dtype=bool)
1126 tf.Tensor([ True], shape=(1,), dtype=bool)
1127 tf.Tensor([ True], shape=(1,), dtype=bool)
1128 tf.Tensor([ True], shape=(1,), dtype=bool)
1129 tf.Tensor([ True], shape=(1,), dtype=bool)
1130 tf.Tensor([ True], shape=(1,), dtype=bool)
1131 tf.Tensor([ True], shape=(1,), dtype=bool)
1132 tf.Tensor([ True], shape=(1,), dtype=bool)
1133 tf.Tensor([ True], shape=(1,), dtype=bool)
1134 tf.Tensor([ True], shape=(1,), dtype=bool)
1135 tf.Tensor([ True], shape=(1,), dtype=bool)
1136 tf.Tensor([ True], shape=(1,), dtype=bool)
1137 tf.Tensor([ True], shape=(1,), dtype=bool)
1138 tf.Tensor([ True], shape=(1,), dtyp

1302 tf.Tensor([ True], shape=(1,), dtype=bool)
1303 tf.Tensor([ True], shape=(1,), dtype=bool)
1304 tf.Tensor([ True], shape=(1,), dtype=bool)
1305 tf.Tensor([ True], shape=(1,), dtype=bool)
1306 tf.Tensor([ True], shape=(1,), dtype=bool)
1307 tf.Tensor([ True], shape=(1,), dtype=bool)
1308 tf.Tensor([ True], shape=(1,), dtype=bool)
1309 tf.Tensor([ True], shape=(1,), dtype=bool)
1310 tf.Tensor([ True], shape=(1,), dtype=bool)
1311 tf.Tensor([ True], shape=(1,), dtype=bool)
1312 tf.Tensor([ True], shape=(1,), dtype=bool)
1313 tf.Tensor([ True], shape=(1,), dtype=bool)
1314 tf.Tensor([ True], shape=(1,), dtype=bool)
1315 tf.Tensor([ True], shape=(1,), dtype=bool)
1316 tf.Tensor([ True], shape=(1,), dtype=bool)
1317 tf.Tensor([ True], shape=(1,), dtype=bool)
1318 tf.Tensor([ True], shape=(1,), dtype=bool)
1319 tf.Tensor([ True], shape=(1,), dtype=bool)
1320 tf.Tensor([False], shape=(1,), dtype=bool)
1321 tf.Tensor([ True], shape=(1,), dtype=bool)
1322 tf.Tensor([ True], shape=(1,), dtyp

1513 tf.Tensor([ True], shape=(1,), dtype=bool)
1514 tf.Tensor([ True], shape=(1,), dtype=bool)
1515 tf.Tensor([ True], shape=(1,), dtype=bool)
1516 tf.Tensor([ True], shape=(1,), dtype=bool)
1517 tf.Tensor([ True], shape=(1,), dtype=bool)
1518 tf.Tensor([ True], shape=(1,), dtype=bool)
1519 tf.Tensor([ True], shape=(1,), dtype=bool)
1520 tf.Tensor([ True], shape=(1,), dtype=bool)
1521 tf.Tensor([ True], shape=(1,), dtype=bool)
1522 tf.Tensor([ True], shape=(1,), dtype=bool)
1523 tf.Tensor([ True], shape=(1,), dtype=bool)
1524 tf.Tensor([ True], shape=(1,), dtype=bool)
1525 tf.Tensor([ True], shape=(1,), dtype=bool)
1526 tf.Tensor([ True], shape=(1,), dtype=bool)
1527 tf.Tensor([ True], shape=(1,), dtype=bool)
1528 tf.Tensor([False], shape=(1,), dtype=bool)
1529 tf.Tensor([ True], shape=(1,), dtype=bool)
1530 tf.Tensor([ True], shape=(1,), dtype=bool)
1531 tf.Tensor([False], shape=(1,), dtype=bool)
1532 tf.Tensor([ True], shape=(1,), dtype=bool)
1533 tf.Tensor([ True], shape=(1,), dtyp

1691 tf.Tensor([ True], shape=(1,), dtype=bool)
1692 tf.Tensor([ True], shape=(1,), dtype=bool)
1693 tf.Tensor([ True], shape=(1,), dtype=bool)
1694 tf.Tensor([ True], shape=(1,), dtype=bool)
1695 tf.Tensor([ True], shape=(1,), dtype=bool)
1696 tf.Tensor([ True], shape=(1,), dtype=bool)
1697 tf.Tensor([ True], shape=(1,), dtype=bool)
1698 tf.Tensor([ True], shape=(1,), dtype=bool)
1699 tf.Tensor([ True], shape=(1,), dtype=bool)
1700 tf.Tensor([ True], shape=(1,), dtype=bool)
1701 tf.Tensor([ True], shape=(1,), dtype=bool)
1702 tf.Tensor([ True], shape=(1,), dtype=bool)
1703 tf.Tensor([ True], shape=(1,), dtype=bool)
1704 tf.Tensor([ True], shape=(1,), dtype=bool)
1705 tf.Tensor([ True], shape=(1,), dtype=bool)
1706 tf.Tensor([ True], shape=(1,), dtype=bool)
1707 tf.Tensor([ True], shape=(1,), dtype=bool)
1708 tf.Tensor([ True], shape=(1,), dtype=bool)
1709 tf.Tensor([ True], shape=(1,), dtype=bool)
1710 tf.Tensor([False], shape=(1,), dtype=bool)
1711 tf.Tensor([ True], shape=(1,), dtyp

1871 tf.Tensor([ True], shape=(1,), dtype=bool)
1872 tf.Tensor([ True], shape=(1,), dtype=bool)
1873 tf.Tensor([ True], shape=(1,), dtype=bool)
1874 tf.Tensor([ True], shape=(1,), dtype=bool)
1875 tf.Tensor([ True], shape=(1,), dtype=bool)
1876 tf.Tensor([ True], shape=(1,), dtype=bool)
1877 tf.Tensor([ True], shape=(1,), dtype=bool)
1878 tf.Tensor([ True], shape=(1,), dtype=bool)
1879 tf.Tensor([False], shape=(1,), dtype=bool)
1880 tf.Tensor([ True], shape=(1,), dtype=bool)
1881 tf.Tensor([ True], shape=(1,), dtype=bool)
1882 tf.Tensor([ True], shape=(1,), dtype=bool)
1883 tf.Tensor([ True], shape=(1,), dtype=bool)
1884 tf.Tensor([ True], shape=(1,), dtype=bool)
1885 tf.Tensor([ True], shape=(1,), dtype=bool)
1886 tf.Tensor([ True], shape=(1,), dtype=bool)
1887 tf.Tensor([ True], shape=(1,), dtype=bool)
1888 tf.Tensor([ True], shape=(1,), dtype=bool)
1889 tf.Tensor([ True], shape=(1,), dtype=bool)
1890 tf.Tensor([ True], shape=(1,), dtype=bool)
1891 tf.Tensor([ True], shape=(1,), dtyp

2051 tf.Tensor([ True], shape=(1,), dtype=bool)
2052 tf.Tensor([ True], shape=(1,), dtype=bool)
2053 tf.Tensor([ True], shape=(1,), dtype=bool)
2054 tf.Tensor([ True], shape=(1,), dtype=bool)
2055 tf.Tensor([ True], shape=(1,), dtype=bool)
2056 tf.Tensor([ True], shape=(1,), dtype=bool)
2057 tf.Tensor([ True], shape=(1,), dtype=bool)
2058 tf.Tensor([ True], shape=(1,), dtype=bool)
2059 tf.Tensor([ True], shape=(1,), dtype=bool)
2060 tf.Tensor([ True], shape=(1,), dtype=bool)
2061 tf.Tensor([ True], shape=(1,), dtype=bool)
2062 tf.Tensor([ True], shape=(1,), dtype=bool)
2063 tf.Tensor([ True], shape=(1,), dtype=bool)
2064 tf.Tensor([ True], shape=(1,), dtype=bool)
2065 tf.Tensor([ True], shape=(1,), dtype=bool)
2066 tf.Tensor([ True], shape=(1,), dtype=bool)
2067 tf.Tensor([ True], shape=(1,), dtype=bool)
2068 tf.Tensor([ True], shape=(1,), dtype=bool)
2069 tf.Tensor([ True], shape=(1,), dtype=bool)
2070 tf.Tensor([ True], shape=(1,), dtype=bool)
2071 tf.Tensor([ True], shape=(1,), dtyp

2230 tf.Tensor([ True], shape=(1,), dtype=bool)
2231 tf.Tensor([ True], shape=(1,), dtype=bool)
2232 tf.Tensor([ True], shape=(1,), dtype=bool)
2233 tf.Tensor([ True], shape=(1,), dtype=bool)
2234 tf.Tensor([ True], shape=(1,), dtype=bool)
2235 tf.Tensor([ True], shape=(1,), dtype=bool)
2236 tf.Tensor([ True], shape=(1,), dtype=bool)
2237 tf.Tensor([ True], shape=(1,), dtype=bool)
2238 tf.Tensor([ True], shape=(1,), dtype=bool)
2239 tf.Tensor([ True], shape=(1,), dtype=bool)
2240 tf.Tensor([ True], shape=(1,), dtype=bool)
2241 tf.Tensor([ True], shape=(1,), dtype=bool)
2242 tf.Tensor([ True], shape=(1,), dtype=bool)
2243 tf.Tensor([ True], shape=(1,), dtype=bool)
2244 tf.Tensor([ True], shape=(1,), dtype=bool)
2245 tf.Tensor([ True], shape=(1,), dtype=bool)
2246 tf.Tensor([ True], shape=(1,), dtype=bool)
2247 tf.Tensor([ True], shape=(1,), dtype=bool)
2248 tf.Tensor([ True], shape=(1,), dtype=bool)
2249 tf.Tensor([ True], shape=(1,), dtype=bool)
2250 tf.Tensor([ True], shape=(1,), dtyp

2411 tf.Tensor([ True], shape=(1,), dtype=bool)
2412 tf.Tensor([ True], shape=(1,), dtype=bool)
2413 tf.Tensor([ True], shape=(1,), dtype=bool)
2414 tf.Tensor([ True], shape=(1,), dtype=bool)
2415 tf.Tensor([ True], shape=(1,), dtype=bool)
2416 tf.Tensor([ True], shape=(1,), dtype=bool)
2417 tf.Tensor([ True], shape=(1,), dtype=bool)
2418 tf.Tensor([ True], shape=(1,), dtype=bool)
2419 tf.Tensor([ True], shape=(1,), dtype=bool)
2420 tf.Tensor([ True], shape=(1,), dtype=bool)
2421 tf.Tensor([ True], shape=(1,), dtype=bool)
2422 tf.Tensor([ True], shape=(1,), dtype=bool)
2423 tf.Tensor([ True], shape=(1,), dtype=bool)
2424 tf.Tensor([ True], shape=(1,), dtype=bool)
2425 tf.Tensor([ True], shape=(1,), dtype=bool)
2426 tf.Tensor([ True], shape=(1,), dtype=bool)
2427 tf.Tensor([ True], shape=(1,), dtype=bool)
2428 tf.Tensor([ True], shape=(1,), dtype=bool)
2429 tf.Tensor([ True], shape=(1,), dtype=bool)
2430 tf.Tensor([ True], shape=(1,), dtype=bool)
2431 tf.Tensor([ True], shape=(1,), dtyp

2623 tf.Tensor([ True], shape=(1,), dtype=bool)
2624 tf.Tensor([ True], shape=(1,), dtype=bool)
2625 tf.Tensor([ True], shape=(1,), dtype=bool)
2626 tf.Tensor([ True], shape=(1,), dtype=bool)
2627 tf.Tensor([ True], shape=(1,), dtype=bool)
2628 tf.Tensor([ True], shape=(1,), dtype=bool)
2629 tf.Tensor([ True], shape=(1,), dtype=bool)
2630 tf.Tensor([ True], shape=(1,), dtype=bool)
2631 tf.Tensor([ True], shape=(1,), dtype=bool)
2632 tf.Tensor([False], shape=(1,), dtype=bool)
2633 tf.Tensor([ True], shape=(1,), dtype=bool)
2634 tf.Tensor([ True], shape=(1,), dtype=bool)
2635 tf.Tensor([ True], shape=(1,), dtype=bool)
2636 tf.Tensor([False], shape=(1,), dtype=bool)
2637 tf.Tensor([ True], shape=(1,), dtype=bool)
2638 tf.Tensor([ True], shape=(1,), dtype=bool)
2639 tf.Tensor([ True], shape=(1,), dtype=bool)
2640 tf.Tensor([ True], shape=(1,), dtype=bool)
2641 tf.Tensor([ True], shape=(1,), dtype=bool)
2642 tf.Tensor([ True], shape=(1,), dtype=bool)
2643 tf.Tensor([ True], shape=(1,), dtyp

2836 tf.Tensor([ True], shape=(1,), dtype=bool)
2837 tf.Tensor([ True], shape=(1,), dtype=bool)
2838 tf.Tensor([ True], shape=(1,), dtype=bool)
2839 tf.Tensor([ True], shape=(1,), dtype=bool)
2840 tf.Tensor([ True], shape=(1,), dtype=bool)
2841 tf.Tensor([ True], shape=(1,), dtype=bool)
2842 tf.Tensor([ True], shape=(1,), dtype=bool)
2843 tf.Tensor([ True], shape=(1,), dtype=bool)
2844 tf.Tensor([ True], shape=(1,), dtype=bool)
2845 tf.Tensor([ True], shape=(1,), dtype=bool)
2846 tf.Tensor([ True], shape=(1,), dtype=bool)
2847 tf.Tensor([ True], shape=(1,), dtype=bool)
2848 tf.Tensor([ True], shape=(1,), dtype=bool)
2849 tf.Tensor([ True], shape=(1,), dtype=bool)
2850 tf.Tensor([ True], shape=(1,), dtype=bool)
2851 tf.Tensor([ True], shape=(1,), dtype=bool)
2852 tf.Tensor([ True], shape=(1,), dtype=bool)
2853 tf.Tensor([ True], shape=(1,), dtype=bool)
2854 tf.Tensor([ True], shape=(1,), dtype=bool)
2855 tf.Tensor([ True], shape=(1,), dtype=bool)
2856 tf.Tensor([ True], shape=(1,), dtyp

3035 tf.Tensor([ True], shape=(1,), dtype=bool)
3036 tf.Tensor([ True], shape=(1,), dtype=bool)
3037 tf.Tensor([ True], shape=(1,), dtype=bool)
3038 tf.Tensor([ True], shape=(1,), dtype=bool)
3039 tf.Tensor([ True], shape=(1,), dtype=bool)
3040 tf.Tensor([ True], shape=(1,), dtype=bool)
3041 tf.Tensor([ True], shape=(1,), dtype=bool)
3042 tf.Tensor([ True], shape=(1,), dtype=bool)
3043 tf.Tensor([ True], shape=(1,), dtype=bool)
3044 tf.Tensor([ True], shape=(1,), dtype=bool)
3045 tf.Tensor([ True], shape=(1,), dtype=bool)
3046 tf.Tensor([ True], shape=(1,), dtype=bool)
3047 tf.Tensor([ True], shape=(1,), dtype=bool)
3048 tf.Tensor([ True], shape=(1,), dtype=bool)
3049 tf.Tensor([ True], shape=(1,), dtype=bool)
3050 tf.Tensor([ True], shape=(1,), dtype=bool)
3051 tf.Tensor([ True], shape=(1,), dtype=bool)
3052 tf.Tensor([ True], shape=(1,), dtype=bool)
3053 tf.Tensor([ True], shape=(1,), dtype=bool)
3054 tf.Tensor([ True], shape=(1,), dtype=bool)
3055 tf.Tensor([ True], shape=(1,), dtyp

3208 tf.Tensor([ True], shape=(1,), dtype=bool)
3209 tf.Tensor([ True], shape=(1,), dtype=bool)
3210 tf.Tensor([ True], shape=(1,), dtype=bool)
3211 tf.Tensor([ True], shape=(1,), dtype=bool)
3212 tf.Tensor([ True], shape=(1,), dtype=bool)
3213 tf.Tensor([ True], shape=(1,), dtype=bool)
3214 tf.Tensor([ True], shape=(1,), dtype=bool)
3215 tf.Tensor([ True], shape=(1,), dtype=bool)
3216 tf.Tensor([ True], shape=(1,), dtype=bool)
3217 tf.Tensor([ True], shape=(1,), dtype=bool)
3218 tf.Tensor([ True], shape=(1,), dtype=bool)
3219 tf.Tensor([ True], shape=(1,), dtype=bool)
3220 tf.Tensor([ True], shape=(1,), dtype=bool)
3221 tf.Tensor([ True], shape=(1,), dtype=bool)
3222 tf.Tensor([ True], shape=(1,), dtype=bool)
3223 tf.Tensor([ True], shape=(1,), dtype=bool)
3224 tf.Tensor([ True], shape=(1,), dtype=bool)
3225 tf.Tensor([ True], shape=(1,), dtype=bool)
3226 tf.Tensor([ True], shape=(1,), dtype=bool)
3227 tf.Tensor([ True], shape=(1,), dtype=bool)
3228 tf.Tensor([ True], shape=(1,), dtyp

3406 tf.Tensor([ True], shape=(1,), dtype=bool)
3407 tf.Tensor([ True], shape=(1,), dtype=bool)
3408 tf.Tensor([ True], shape=(1,), dtype=bool)
3409 tf.Tensor([ True], shape=(1,), dtype=bool)
3410 tf.Tensor([ True], shape=(1,), dtype=bool)
3411 tf.Tensor([ True], shape=(1,), dtype=bool)
3412 tf.Tensor([ True], shape=(1,), dtype=bool)
3413 tf.Tensor([ True], shape=(1,), dtype=bool)
3414 tf.Tensor([ True], shape=(1,), dtype=bool)
3415 tf.Tensor([ True], shape=(1,), dtype=bool)
3416 tf.Tensor([ True], shape=(1,), dtype=bool)
3417 tf.Tensor([ True], shape=(1,), dtype=bool)
3418 tf.Tensor([ True], shape=(1,), dtype=bool)
3419 tf.Tensor([ True], shape=(1,), dtype=bool)
3420 tf.Tensor([ True], shape=(1,), dtype=bool)
3421 tf.Tensor([ True], shape=(1,), dtype=bool)
3422 tf.Tensor([ True], shape=(1,), dtype=bool)
3423 tf.Tensor([ True], shape=(1,), dtype=bool)
3424 tf.Tensor([ True], shape=(1,), dtype=bool)
3425 tf.Tensor([ True], shape=(1,), dtype=bool)
3426 tf.Tensor([ True], shape=(1,), dtyp

3583 tf.Tensor([ True], shape=(1,), dtype=bool)
3584 tf.Tensor([ True], shape=(1,), dtype=bool)
3585 tf.Tensor([ True], shape=(1,), dtype=bool)
3586 tf.Tensor([ True], shape=(1,), dtype=bool)
3587 tf.Tensor([ True], shape=(1,), dtype=bool)
3588 tf.Tensor([ True], shape=(1,), dtype=bool)
3589 tf.Tensor([ True], shape=(1,), dtype=bool)
3590 tf.Tensor([ True], shape=(1,), dtype=bool)
3591 tf.Tensor([ True], shape=(1,), dtype=bool)
3592 tf.Tensor([ True], shape=(1,), dtype=bool)
3593 tf.Tensor([ True], shape=(1,), dtype=bool)
3594 tf.Tensor([ True], shape=(1,), dtype=bool)
3595 tf.Tensor([ True], shape=(1,), dtype=bool)
3596 tf.Tensor([ True], shape=(1,), dtype=bool)
3597 tf.Tensor([ True], shape=(1,), dtype=bool)
3598 tf.Tensor([False], shape=(1,), dtype=bool)
3599 tf.Tensor([ True], shape=(1,), dtype=bool)
3600 tf.Tensor([False], shape=(1,), dtype=bool)
3601 tf.Tensor([ True], shape=(1,), dtype=bool)
3602 tf.Tensor([ True], shape=(1,), dtype=bool)
3603 tf.Tensor([ True], shape=(1,), dtyp

3789 tf.Tensor([ True], shape=(1,), dtype=bool)
3790 tf.Tensor([ True], shape=(1,), dtype=bool)
3791 tf.Tensor([ True], shape=(1,), dtype=bool)
3792 tf.Tensor([ True], shape=(1,), dtype=bool)
3793 tf.Tensor([ True], shape=(1,), dtype=bool)
3794 tf.Tensor([ True], shape=(1,), dtype=bool)
3795 tf.Tensor([ True], shape=(1,), dtype=bool)
3796 tf.Tensor([ True], shape=(1,), dtype=bool)
3797 tf.Tensor([ True], shape=(1,), dtype=bool)
3798 tf.Tensor([ True], shape=(1,), dtype=bool)
3799 tf.Tensor([ True], shape=(1,), dtype=bool)
3800 tf.Tensor([ True], shape=(1,), dtype=bool)
3801 tf.Tensor([ True], shape=(1,), dtype=bool)
3802 tf.Tensor([ True], shape=(1,), dtype=bool)
3803 tf.Tensor([ True], shape=(1,), dtype=bool)
3804 tf.Tensor([ True], shape=(1,), dtype=bool)
3805 tf.Tensor([ True], shape=(1,), dtype=bool)
3806 tf.Tensor([ True], shape=(1,), dtype=bool)
3807 tf.Tensor([ True], shape=(1,), dtype=bool)
3808 tf.Tensor([ True], shape=(1,), dtype=bool)
3809 tf.Tensor([False], shape=(1,), dtyp

3960 tf.Tensor([ True], shape=(1,), dtype=bool)
3961 tf.Tensor([ True], shape=(1,), dtype=bool)
3962 tf.Tensor([ True], shape=(1,), dtype=bool)
3963 tf.Tensor([ True], shape=(1,), dtype=bool)
3964 tf.Tensor([ True], shape=(1,), dtype=bool)
3965 tf.Tensor([ True], shape=(1,), dtype=bool)
3966 tf.Tensor([ True], shape=(1,), dtype=bool)
3967 tf.Tensor([ True], shape=(1,), dtype=bool)
3968 tf.Tensor([ True], shape=(1,), dtype=bool)
3969 tf.Tensor([ True], shape=(1,), dtype=bool)
3970 tf.Tensor([ True], shape=(1,), dtype=bool)
3971 tf.Tensor([ True], shape=(1,), dtype=bool)
3972 tf.Tensor([ True], shape=(1,), dtype=bool)
3973 tf.Tensor([ True], shape=(1,), dtype=bool)
3974 tf.Tensor([ True], shape=(1,), dtype=bool)
3975 tf.Tensor([ True], shape=(1,), dtype=bool)
3976 tf.Tensor([ True], shape=(1,), dtype=bool)
3977 tf.Tensor([ True], shape=(1,), dtype=bool)
3978 tf.Tensor([ True], shape=(1,), dtype=bool)
3979 tf.Tensor([ True], shape=(1,), dtype=bool)
3980 tf.Tensor([ True], shape=(1,), dtyp

4171 tf.Tensor([ True], shape=(1,), dtype=bool)
4172 tf.Tensor([ True], shape=(1,), dtype=bool)
4173 tf.Tensor([ True], shape=(1,), dtype=bool)
4174 tf.Tensor([ True], shape=(1,), dtype=bool)
4175 tf.Tensor([ True], shape=(1,), dtype=bool)
4176 tf.Tensor([ True], shape=(1,), dtype=bool)
4177 tf.Tensor([False], shape=(1,), dtype=bool)
4178 tf.Tensor([ True], shape=(1,), dtype=bool)
4179 tf.Tensor([ True], shape=(1,), dtype=bool)
4180 tf.Tensor([ True], shape=(1,), dtype=bool)
4181 tf.Tensor([ True], shape=(1,), dtype=bool)
4182 tf.Tensor([ True], shape=(1,), dtype=bool)
4183 tf.Tensor([ True], shape=(1,), dtype=bool)
4184 tf.Tensor([ True], shape=(1,), dtype=bool)
4185 tf.Tensor([ True], shape=(1,), dtype=bool)
4186 tf.Tensor([ True], shape=(1,), dtype=bool)
4187 tf.Tensor([ True], shape=(1,), dtype=bool)
4188 tf.Tensor([ True], shape=(1,), dtype=bool)
4189 tf.Tensor([ True], shape=(1,), dtype=bool)
4190 tf.Tensor([ True], shape=(1,), dtype=bool)
4191 tf.Tensor([ True], shape=(1,), dtyp

4374 tf.Tensor([ True], shape=(1,), dtype=bool)
4375 tf.Tensor([ True], shape=(1,), dtype=bool)
4376 tf.Tensor([ True], shape=(1,), dtype=bool)
4377 tf.Tensor([ True], shape=(1,), dtype=bool)
4378 tf.Tensor([ True], shape=(1,), dtype=bool)
4379 tf.Tensor([ True], shape=(1,), dtype=bool)
4380 tf.Tensor([ True], shape=(1,), dtype=bool)
4381 tf.Tensor([False], shape=(1,), dtype=bool)
4382 tf.Tensor([ True], shape=(1,), dtype=bool)
4383 tf.Tensor([ True], shape=(1,), dtype=bool)
4384 tf.Tensor([ True], shape=(1,), dtype=bool)
4385 tf.Tensor([ True], shape=(1,), dtype=bool)
4386 tf.Tensor([ True], shape=(1,), dtype=bool)
4387 tf.Tensor([ True], shape=(1,), dtype=bool)
4388 tf.Tensor([ True], shape=(1,), dtype=bool)
4389 tf.Tensor([ True], shape=(1,), dtype=bool)
4390 tf.Tensor([ True], shape=(1,), dtype=bool)
4391 tf.Tensor([ True], shape=(1,), dtype=bool)
4392 tf.Tensor([ True], shape=(1,), dtype=bool)
4393 tf.Tensor([ True], shape=(1,), dtype=bool)
4394 tf.Tensor([ True], shape=(1,), dtyp

4553 tf.Tensor([ True], shape=(1,), dtype=bool)
4554 tf.Tensor([ True], shape=(1,), dtype=bool)
4555 tf.Tensor([ True], shape=(1,), dtype=bool)
4556 tf.Tensor([ True], shape=(1,), dtype=bool)
4557 tf.Tensor([ True], shape=(1,), dtype=bool)
4558 tf.Tensor([ True], shape=(1,), dtype=bool)
4559 tf.Tensor([ True], shape=(1,), dtype=bool)
4560 tf.Tensor([ True], shape=(1,), dtype=bool)
4561 tf.Tensor([ True], shape=(1,), dtype=bool)
4562 tf.Tensor([ True], shape=(1,), dtype=bool)
4563 tf.Tensor([ True], shape=(1,), dtype=bool)
4564 tf.Tensor([ True], shape=(1,), dtype=bool)
4565 tf.Tensor([ True], shape=(1,), dtype=bool)
4566 tf.Tensor([ True], shape=(1,), dtype=bool)
4567 tf.Tensor([ True], shape=(1,), dtype=bool)
4568 tf.Tensor([ True], shape=(1,), dtype=bool)
4569 tf.Tensor([ True], shape=(1,), dtype=bool)
4570 tf.Tensor([ True], shape=(1,), dtype=bool)
4571 tf.Tensor([ True], shape=(1,), dtype=bool)
4572 tf.Tensor([False], shape=(1,), dtype=bool)
4573 tf.Tensor([ True], shape=(1,), dtyp

4765 tf.Tensor([ True], shape=(1,), dtype=bool)
4766 tf.Tensor([ True], shape=(1,), dtype=bool)
4767 tf.Tensor([ True], shape=(1,), dtype=bool)
4768 tf.Tensor([ True], shape=(1,), dtype=bool)
4769 tf.Tensor([ True], shape=(1,), dtype=bool)
4770 tf.Tensor([ True], shape=(1,), dtype=bool)
4771 tf.Tensor([ True], shape=(1,), dtype=bool)
4772 tf.Tensor([ True], shape=(1,), dtype=bool)
4773 tf.Tensor([ True], shape=(1,), dtype=bool)
4774 tf.Tensor([ True], shape=(1,), dtype=bool)
4775 tf.Tensor([ True], shape=(1,), dtype=bool)
4776 tf.Tensor([ True], shape=(1,), dtype=bool)
4777 tf.Tensor([ True], shape=(1,), dtype=bool)
4778 tf.Tensor([ True], shape=(1,), dtype=bool)
4779 tf.Tensor([ True], shape=(1,), dtype=bool)
4780 tf.Tensor([ True], shape=(1,), dtype=bool)
4781 tf.Tensor([ True], shape=(1,), dtype=bool)
4782 tf.Tensor([ True], shape=(1,), dtype=bool)
4783 tf.Tensor([ True], shape=(1,), dtype=bool)
4784 tf.Tensor([ True], shape=(1,), dtype=bool)
4785 tf.Tensor([ True], shape=(1,), dtyp

4954 tf.Tensor([ True], shape=(1,), dtype=bool)
4955 tf.Tensor([ True], shape=(1,), dtype=bool)
4956 tf.Tensor([ True], shape=(1,), dtype=bool)
4957 tf.Tensor([False], shape=(1,), dtype=bool)
4958 tf.Tensor([ True], shape=(1,), dtype=bool)
4959 tf.Tensor([ True], shape=(1,), dtype=bool)
4960 tf.Tensor([ True], shape=(1,), dtype=bool)
4961 tf.Tensor([ True], shape=(1,), dtype=bool)
4962 tf.Tensor([ True], shape=(1,), dtype=bool)
4963 tf.Tensor([ True], shape=(1,), dtype=bool)
4964 tf.Tensor([ True], shape=(1,), dtype=bool)
4965 tf.Tensor([ True], shape=(1,), dtype=bool)
4966 tf.Tensor([ True], shape=(1,), dtype=bool)
4967 tf.Tensor([ True], shape=(1,), dtype=bool)
4968 tf.Tensor([ True], shape=(1,), dtype=bool)
4969 tf.Tensor([ True], shape=(1,), dtype=bool)
4970 tf.Tensor([ True], shape=(1,), dtype=bool)
4971 tf.Tensor([ True], shape=(1,), dtype=bool)
4972 tf.Tensor([ True], shape=(1,), dtype=bool)
4973 tf.Tensor([ True], shape=(1,), dtype=bool)
4974 tf.Tensor([ True], shape=(1,), dtyp

5147 tf.Tensor([ True], shape=(1,), dtype=bool)
5148 tf.Tensor([ True], shape=(1,), dtype=bool)
5149 tf.Tensor([ True], shape=(1,), dtype=bool)
5150 tf.Tensor([ True], shape=(1,), dtype=bool)
5151 tf.Tensor([ True], shape=(1,), dtype=bool)
5152 tf.Tensor([ True], shape=(1,), dtype=bool)
5153 tf.Tensor([ True], shape=(1,), dtype=bool)
5154 tf.Tensor([ True], shape=(1,), dtype=bool)
5155 tf.Tensor([ True], shape=(1,), dtype=bool)
5156 tf.Tensor([ True], shape=(1,), dtype=bool)
5157 tf.Tensor([ True], shape=(1,), dtype=bool)
5158 tf.Tensor([ True], shape=(1,), dtype=bool)
5159 tf.Tensor([ True], shape=(1,), dtype=bool)
5160 tf.Tensor([ True], shape=(1,), dtype=bool)
5161 tf.Tensor([ True], shape=(1,), dtype=bool)
5162 tf.Tensor([ True], shape=(1,), dtype=bool)
5163 tf.Tensor([ True], shape=(1,), dtype=bool)
5164 tf.Tensor([ True], shape=(1,), dtype=bool)
5165 tf.Tensor([ True], shape=(1,), dtype=bool)
5166 tf.Tensor([ True], shape=(1,), dtype=bool)
5167 tf.Tensor([ True], shape=(1,), dtyp